### ISSUE TITLE
how can i configure proxy in client?

### ISSUE THREAD

**Issue by ghost** [Neembuu-Uploader/neembuu-uploader#1]
https://github.com/Neembuu-Uploader/neembuu-uploader/blob/8e52583e6e6184e9817af3d24ba9859a4472f0fb/modules/nu-app-base/src/neembuu/uploader/settings/Settings.java

I noticed there is proxy setting on the source but i cant find configure panel for proxy in client.
How can i do that?
![bb](https://cloud.githubusercontent.com/assets/16120391/11535129/cbd33ea6-9955-11e5-8dac-87a8b51c717b.png)

**Comment by Paralytic** [comment]
Unfortunately, all long-standing developers related to the project have abandoned it and this project is therefore effectively inactive. All development on this application has been stopped indefinitely.
