### ISSUE TITLE
Updating Plugin windows not closed

### ISSUE THREAD

**Issue by ghost** [Neembuu-Uploader/neembuu-uploader#3]
![bb](https://cloud.githubusercontent.com/assets/16120391/11535241/6000e3a8-9956-11e5-9ce3-ffd973d8df27.png)

it shows up and not closed when updating list of supported file host

**Comment by Paralytic** [comment]
Unfortunately, all long-standing developers related to the project have abandoned it and this project is therefore effectively inactive. All development on this application has been stopped indefinitely.
